# Book table
MovieAppTable:
  Type: "AWS::DynamoDB::Table"
  Properties: 
    AttributeDefinitions: 
      - AttributeName: "name"
        AttributeType: "S"
    BillingMode: "PAY_PER_REQUEST"
    KeySchema: 
      - AttributeName: "name"
        KeyType: "HASH"
    Tags: 
      - Key: "name"
        Value: "moive-table" 
